import { join } from "node:path";
import { DIST } from "./build";

/**
 * Generate the thin @semideus/code npm wrapper into dist/npm/ (ADR-0010,
 * packaging brief step 4). The wrapper ships no workspace code: a bin shim, a
 * postinstall that downloads the platform binary for its own version and
 * verifies it against the SHA-256 checksums baked in here — a release's
 * wrapper can only ever install that release's binaries.
 *
 * install.js and the shim run under the user's Node (npm runs postinstall
 * with Node) — the one deliberate exception to the Bun-only rule.
 */

/** Artifact per platform/arch, or null when unsupported. Mirrors build.ts TARGETS. */
export function artifactFor(platform: string, arch: string): string | null {
  if (platform === "linux" && arch === "x64") return "daimon-linux-x64";
  if (platform === "darwin" && arch === "arm64") return "daimon-darwin-arm64";
  if (platform === "darwin" && arch === "x64") return "daimon-darwin-x64";
  if (platform === "win32" && arch === "x64") return "daimon-windows-x64.exe";
  return null;
}

export interface WrapperInput {
  version: string;
  /** artifact name → sha256 hex, from dist/SHA256SUMS. */
  checksums: Record<string, string>;
  /** GitHub repo url (https://github.com/owner/repo) or null until a remote exists. */
  repoUrl: string | null;
}

export function parseSha256Sums(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const match = line.match(/^([0-9a-f]{64})\s+(\S+)$/);
    if (match?.[1] && match[2]) out[match[2]] = match[1];
  }
  return out;
}

export function renderWrapper(input: WrapperInput): Record<string, string> {
  const { version, checksums, repoUrl } = input;
  const releaseBase = repoUrl ? `${repoUrl}/releases/download/v${version}` : null;

  const packageJson = `${JSON.stringify(
    {
      name: "@semideus/code",
      version,
      description:
        "daimon — a terminal coding agent that teaches while it works. Thin installer; the binary is downloaded and checksum-verified on install.",
      license: "Apache-2.0",
      bin: { daimon: "bin/daimon.js" },
      files: ["bin", "install.js", "README.md"],
      scripts: { postinstall: "node install.js" },
      engines: { node: ">=18" },
      ...(repoUrl ? { repository: { type: "git", url: `git+${repoUrl}.git` } } : {}),
    },
    null,
    2,
  )}\n`;

  const installJs = `// Generated by scripts/build-npm.ts — do not edit.
const { createHash } = require("node:crypto");
const { chmodSync, mkdirSync, writeFileSync } = require("node:fs");
const { join } = require("node:path");

const VERSION = ${JSON.stringify(version)};
const CHECKSUMS = ${JSON.stringify(checksums, null, 2)};
const RELEASE_BASE = ${JSON.stringify(releaseBase)};

const ARTIFACTS = {
  "linux-x64": "daimon-linux-x64",
  "darwin-arm64": "daimon-darwin-arm64",
  "darwin-x64": "daimon-darwin-x64",
  "win32-x64": "daimon-windows-x64.exe",
};

async function main() {
  const artifact = ARTIFACTS[\`\${process.platform}-\${process.arch}\`];
  if (!artifact) {
    console.error(
      \`daimon: unsupported platform \${process.platform}-\${process.arch} — \` +
        \`supported: \${Object.keys(ARTIFACTS).join(", ")}\`,
    );
    process.exit(1);
  }
  const base = process.env.DAIMON_BINARY_URL ?? RELEASE_BASE;
  if (!base) {
    console.error("daimon: no release URL baked in — set DAIMON_BINARY_URL to a base URL");
    process.exit(1);
  }
  const url = \`\${base.replace(/\\/$/, "")}/\${artifact}\`;
  console.log(\`daimon \${VERSION}: downloading \${url}\`);
  const res = await fetch(url);
  if (!res.ok) {
    console.error(\`daimon: download failed — \${res.status} \${res.statusText}\`);
    process.exit(1);
  }
  const bytes = Buffer.from(await res.arrayBuffer());

  const expected = CHECKSUMS[artifact];
  const actual = createHash("sha256").update(bytes).digest("hex");
  if (actual !== expected) {
    console.error(
      \`daimon: checksum mismatch for \${artifact} — refusing to install\\n\` +
        \`  expected \${expected}\\n  got      \${actual}\`,
    );
    process.exit(1);
  }

  const vendor = join(__dirname, "vendor");
  mkdirSync(vendor, { recursive: true });
  const target = join(vendor, process.platform === "win32" ? "daimon.exe" : "daimon");
  writeFileSync(target, bytes);
  chmodSync(target, 0o755);
  console.log(\`daimon \${VERSION}: installed \${artifact} (sha256 verified)\`);
}

main().catch((err) => {
  console.error(\`daimon: install failed — \${err?.message ?? err}\`);
  process.exit(1);
});
`;

  const binShim = `#!/usr/bin/env node
// Generated by scripts/build-npm.ts — do not edit.
const { spawnSync } = require("node:child_process");
const { existsSync } = require("node:fs");
const { join } = require("node:path");

const binary = join(
  __dirname,
  "..",
  "vendor",
  process.platform === "win32" ? "daimon.exe" : "daimon",
);
if (!existsSync(binary)) {
  console.error("daimon: binary missing — reinstall @semideus/code (postinstall fetches it)");
  process.exit(1);
}
const result = spawnSync(binary, process.argv.slice(2), { stdio: "inherit" });
process.exit(result.status ?? 1);
`;

  const readme = `# @semideus/code

daimon — a terminal coding agent that teaches while it works.

This package is a thin installer: on install it downloads the daimon binary for
your platform and verifies it against a pinned SHA-256 checksum. Apache-2.0.

\`\`\`bash
npm install -g @semideus/code
daimon
\`\`\`
`;

  return {
    "package.json": packageJson,
    "install.js": installJs,
    "bin/daimon.js": binShim,
    "README.md": readme,
  };
}

if (import.meta.main) {
  const cliPkg = (await Bun.file(
    join(import.meta.dir, "../packages/cli/package.json"),
  ).json()) as Record<string, unknown>;
  const sumsFile = Bun.file(join(DIST, "SHA256SUMS"));
  if (!(await sumsFile.exists())) {
    console.error("dist/SHA256SUMS missing — run `bun run build` first");
    process.exit(1);
  }
  const repo = cliPkg.repository as { url?: string } | undefined;
  const files = renderWrapper({
    version: String(cliPkg.version),
    checksums: parseSha256Sums(await sumsFile.text()),
    repoUrl: repo?.url?.replace(/^git\+/, "").replace(/\.git$/, "") ?? null,
  });
  const out = join(DIST, "npm");
  for (const [name, content] of Object.entries(files)) {
    await Bun.write(join(out, name), content);
  }
  console.log(`wrote dist/npm/ (${Object.keys(files).length} files, version ${cliPkg.version})`);
  if (!repo?.url) {
    console.log(
      "note: no repository.url in packages/cli/package.json — installs will need DAIMON_BINARY_URL until the remote exists (release-pipeline brief)",
    );
  }
}
